#GET http://localhost:5000
#GET http://localhost:5000/api/v1/bootcamps
#GET http://localhost:5000/api/v1/bootcamps/67c2960aca4d0738f6ec629a
#POST http://localhost:5000/api/v1/bootcamps
#PUT http://localhost:5000/api/v1/bootcamps/6
#DELETE http://localhost:5000/api/v1/bootcamps/67c51715edc1188a6d2bf860

# Filter by city
#GET http://localhost:5000/api/v1/bootcamps?location.city=Toronto
# Filter by avgCost using MongoDB operators: https://www.mongodb.com/docs/manual/reference/operator/query-comparison/
#GET http://localhost:5000/api/v1/bootcamps?avgCost[lt]=10000
# Filter by careers
#GET http://localhost:5000/api/v1/bootcamps?careers[in]=Mobile Development

// Select
#GET http://localhost:5000/api/v1/bootcamps?select=name
#GET http://localhost:5000/api/v1/bootcamps?select=name,description

// Sort
#GET http://localhost:5000/api/v1/bootcamps?sort=avgCost&select=name,avgCost
#GET http://localhost:5000/api/v1/bootcamps?sort=-avgCost&select=name,avgCost
#GET http://localhost:5000/api/v1/bootcamps?sort=-avgCost&select=name,avgCost&housing=true

# Pagination
#GET http://localhost:5000/api/v1/bootcamps?limit=2&select=name&page=1

#POST http://localhost:5000/api/v1/bootcamps
#Content-Type: application/json
#
#{
#  "name": "Devcentral Bootcamp",
#  "description": "Is coding your passion? Codemasters will give you the skills and the tools to become the best developer possible. We specialize in front end and full stack web development",
#  "website": "https://devcentral.com",
#  "phone": "(444) 444-4444",
#  "email": "enroll@devcentral.com",
#  "address": "615 Rymal Road East, Hamilton, ON L8W 0B6",
#  "careers": [
#    "Mobile Development",
#    "Web Development",
#    "Data Science",
#    "Business"
#  ],
#  "housing": false,
#  "jobAssistance": true,
#  "jobGuarantee": true,
#  "acceptGi": true
#}


#GET http://localhost:5000/api/v1/bootcamps/radius/L8W0B6/150


#-------------- Courses ----------------
#GET http://localhost:5000/api/v1/courses
#GET http://localhost:5000/api/v1/bootcamps/5d725a037b292f5f8ceff787/courses
